package View;

import ClassController.principalController;
import ClassController.profesoresController;
import Model.profesoresModel;

public class profesoresView extends javax.swing.JFrame {

    profesoresModel profesor = new profesoresModel();
    principalController pController = new principalController();

    public profesoresView() {
        initComponents();
        tablaProfesores.setModel(profesor.mostrarProfesores());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelProfesores = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        panelControl = new javax.swing.JPanel();
        lbId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lbNif = new javax.swing.JLabel();
        txtNif = new javax.swing.JTextField();
        lbNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lbApellido = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        lbCiudad = new javax.swing.JLabel();
        txtCiudad = new javax.swing.JTextField();
        lbDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        lbTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lbIdDepartamento = new javax.swing.JLabel();
        txtIdDepartamento = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnInsertar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProfesores = new javax.swing.JTable();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Panel de Profesores");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelProfesores.setBackground(new java.awt.Color(255, 255, 255));
        panelProfesores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitulo.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("Panel Profesores");
        panelProfesores.add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 730, 32));

        panelControl.setBackground(new java.awt.Color(204, 204, 255));
        panelControl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbId.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        lbId.setText("Id");
        panelControl.add(lbId, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 24, 42, 25));

        txtId.setEditable(false);
        txtId.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        txtId.setToolTipText("");
        panelControl.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 26, 215, -1));

        lbNif.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        lbNif.setText("NIF");
        panelControl.add(lbNif, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 55, 42, 25));

        txtNif.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        txtNif.setNextFocusableComponent(txtNombre);
        panelControl.add(txtNif, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 57, 209, -1));

        lbNombre.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        lbNombre.setText("Nombre");
        panelControl.add(lbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 85, -1, 25));

        txtNombre.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        txtNombre.setNextFocusableComponent(txtApellido);
        panelControl.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 87, 206, -1));

        lbApellido.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        lbApellido.setText("Apellido");
        panelControl.add(lbApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 115, -1, 25));

        txtApellido.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        txtApellido.setNextFocusableComponent(txtCiudad);
        panelControl.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 117, 207, -1));

        lbCiudad.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        lbCiudad.setText("Ciudad");
        panelControl.add(lbCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 24, -1, 25));

        txtCiudad.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        txtCiudad.setNextFocusableComponent(txtDireccion);
        panelControl.add(txtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 26, 196, -1));

        lbDireccion.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        lbDireccion.setText("Dirección");
        panelControl.add(lbDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 55, -1, 25));

        txtDireccion.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        txtDireccion.setNextFocusableComponent(txtTelefono);
        panelControl.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 57, 189, -1));

        lbTelefono.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        lbTelefono.setText("Teléfono");
        panelControl.add(lbTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 85, -1, 25));

        txtTelefono.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        txtTelefono.setNextFocusableComponent(txtIdDepartamento);
        panelControl.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 87, 186, -1));

        lbIdDepartamento.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        lbIdDepartamento.setText("Id Departamento");
        panelControl.add(lbIdDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 115, -1, 25));

        txtIdDepartamento.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        txtIdDepartamento.setNextFocusableComponent(btnInsertar);
        panelControl.add(txtIdDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 117, 146, -1));

        btnEliminar.setBackground(new java.awt.Color(153, 153, 191));
        btnEliminar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/basura.png"))); // NOI18N
        btnEliminar.setText(" Eliminar");
        btnEliminar.setToolTipText("Eliminar Profesores");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setMaximumSize(new java.awt.Dimension(135, 30));
        btnEliminar.setMinimumSize(new java.awt.Dimension(135, 30));
        btnEliminar.setNextFocusableComponent(btnVolver);
        btnEliminar.setPreferredSize(new java.awt.Dimension(135, 30));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        panelControl.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 164, -1, -1));

        btnModificar.setBackground(new java.awt.Color(153, 153, 191));
        btnModificar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton-editar.png"))); // NOI18N
        btnModificar.setText(" Modificar");
        btnModificar.setToolTipText("Modificar Profesores");
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.setNextFocusableComponent(btnEliminar);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        panelControl.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 164, -1, -1));

        btnInsertar.setBackground(new java.awt.Color(153, 153, 191));
        btnInsertar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnInsertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/anadir.png"))); // NOI18N
        btnInsertar.setText(" Insertar");
        btnInsertar.setToolTipText("Insertar Profesores");
        btnInsertar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInsertar.setMaximumSize(new java.awt.Dimension(135, 30));
        btnInsertar.setMinimumSize(new java.awt.Dimension(135, 30));
        btnInsertar.setNextFocusableComponent(btnModificar);
        btnInsertar.setPreferredSize(new java.awt.Dimension(135, 30));
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        panelControl.add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 164, -1, -1));

        panelProfesores.add(panelControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 700, 200));

        tablaProfesores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaProfesores.setSelectionBackground(new java.awt.Color(204, 204, 255));
        tablaProfesores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProfesoresMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaProfesores);

        panelProfesores.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 700, 260));

        btnVolver.setBackground(new java.awt.Color(153, 153, 191));
        btnVolver.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/back-arrow.png"))); // NOI18N
        btnVolver.setText(" Volver");
        btnVolver.setToolTipText("Panel Principal");
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.setNextFocusableComponent(txtNif);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        panelProfesores.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 540, -1, 30));

        getContentPane().add(panelProfesores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int seleccionarFila = tablaProfesores.getSelectedRow();
        String idString = (String) tablaProfesores.getValueAt(seleccionarFila, 0);
        profesoresController pControl = new profesoresController();
        pControl.botonEliminar(seleccionarFila, idString);
        tablaProfesores.setModel(profesor.mostrarProfesores());
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        profesoresController proControl = new profesoresController();
        String nif = txtNif.getText();
        String nombre = txtNombre.getText();
        String apellido = txtApellido.getText();
        String ciudad = txtCiudad.getText();
        String direccion = txtDireccion.getText();
        String telefono = txtTelefono.getText();
        String departamento = txtIdDepartamento.getText();
        String idProfesor = txtId.getText();
        proControl.botonModificar(nif, nombre, apellido, ciudad, direccion, telefono, departamento, idProfesor);
        tablaProfesores.setModel(profesor.mostrarProfesores());
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        profesoresController proControl = new profesoresController();
        String nif = txtNif.getText();
        String nombre = txtNombre.getText();
        String apellido = txtApellido.getText();
        String ciudad = txtCiudad.getText();
        String direccion = txtDireccion.getText();
        String telefono = txtTelefono.getText();
        String departamento = txtIdDepartamento.getText();
        proControl.botonInsertar(nif, nombre, apellido, ciudad, direccion, telefono, departamento);
        tablaProfesores.setModel(profesor.mostrarProfesores());
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void tablaProfesoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProfesoresMouseClicked
        int seleccionar = tablaProfesores.getSelectedRow();
        txtId.setText(tablaProfesores.getValueAt(seleccionar, 0) + "");
        txtNif.setText(tablaProfesores.getValueAt(seleccionar, 1) + "");
        txtNombre.setText(tablaProfesores.getValueAt(seleccionar, 2) + "");
        txtApellido.setText(tablaProfesores.getValueAt(seleccionar, 3) + "");
        txtCiudad.setText(tablaProfesores.getValueAt(seleccionar, 4) + "");
        txtDireccion.setText(tablaProfesores.getValueAt(seleccionar, 5) + "");
        txtTelefono.setText(tablaProfesores.getValueAt(seleccionar, 6) + "");
        txtIdDepartamento.setText(tablaProfesores.getValueAt(seleccionar, 7) + "");
    }//GEN-LAST:event_tablaProfesoresMouseClicked

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        pController.mostrarPanelPrincipal();
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    public void limpiarProfesores() {
        txtId.setText("");
        txtNif.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtCiudad.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtIdDepartamento.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbApellido;
    private javax.swing.JLabel lbCiudad;
    private javax.swing.JLabel lbDireccion;
    private javax.swing.JLabel lbId;
    private javax.swing.JLabel lbIdDepartamento;
    private javax.swing.JLabel lbNif;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbTelefono;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JPanel panelControl;
    private javax.swing.JPanel panelProfesores;
    private javax.swing.JTable tablaProfesores;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdDepartamento;
    private javax.swing.JTextField txtNif;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
